#! /bin/sh

prefix=~/.wasicaml

run_test() {
    rm -f t_byte t_byte.* t_wasm t_wasm.*
    printf "Test %s: " "$t"
    "$prefix"/bin/ocamlc -g -use-runtime ./testruntime -I testprint -o t_byte testprint.cma "$t" || return
    ../src/wasicaml/wasicaml -q -o t_wasm.wasm -cclib "testprint/libtestprint.a" t_byte || return
    printf "build OK\n"
    ./testruntime t_byte >t_byte.out || { echo "t_byte: bad exit code"; return 1; }
    $prefix/bin/wasi_run ./t_wasm.wasm ./t_wasm.wasm >t_wasm.out || { echo "t_wasm: bad exit code"; return 1; }
    if ! cmp t_byte.out t_wasm.out; then
        printf "Test %s: DIFFERENT RESULTS\n" "$t";
        return 1
    fi
    printf "Test %s: results OK\n" "$t"
}

bad=0
if [ $# -eq 0 ]; then
    for t in $(ls *.ml); do
        run_test "$t" || bad=1
    done
else
    for t in "$@"; do
        run_test "$t" || bad=1
    done
fi

if [ $bad -gt 0 ]; then
    echo "ERRORS EXIST\n" >&2
    exit 1
fi
