#! /bin/bash

set -e

major="32"
minor="0"

case "$(uname)" in
     Darwin)
         variant="macos" ;;
     Linux)
         variant="linux" ;;
     MinGW)
         variant="mingw" ;;
     *)
         echo "Error: Unknown OS" >&2
         exit 2
         ;;
esac

base="wasi-sdk-${major}.${minor}"
file="${base}-${variant}.tar.gz"
arch=$(uname -m)
url="https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-$major/$base-$arch-macos.tar.gz"

if [ ! -f "$file" ]; then
    curl -o "$file" -L "$url"
fi
mkdir -p lib
cd lib
if [ ! -f "$base" ]; then
    tar xzf "../$file"
fi
rm -f wasi-sdk
ln -s "$base" wasi-sdk
