#! /bin/bash

set -e

version="v0.25.0"
arch="x86_64"   # sorry, Brian

case "$(uname)" in
     Darwin)
         variant="macos"; suffix=tar.xz ;;
     Linux)
         variant="linux"; suffix=tar.xz ;;
     MinGW)
         variant="mingw"; suffix=zip ;;
     *)
         echo "Error: Unknown OS" >&2
         exit 2
         ;;
esac

base="wasmtime-${version}-${arch}-${variant}"
file="${base}.${suffix}"
url="https://github.com/bytecodealliance/wasmtime/releases/download/${version}/$file"

if [ ! -f "$file" ]; then
    curl -o "$file" -L "$url"
fi
mkdir -p lib/wasicaml
cd lib/wasicaml
if [ ! -f "$base" ]; then
    case "$suffix" in
        tar.xz)
            tar -xJf "../../$file" ;;
        zip)
            unzip "../../$file" ;;
        *)
            echo "Unknown file suffix: $suffix" >&2; exit 2 ;;
    esac
fi
rm -f wasmtime
ln -s "$base" wasmtime
