#! /bin/sh

export WASICAML='%ROOT%'
export WASICAML_CWD=`pwd`

opts=""
if node --experimental-wasm-bigint -e '' >/dev/null 2>&1; then
	opts=--experimental-wasm-bigint
fi

exec node --stack-size=$(( $(ulimit -s) - 256)) --no-warnings $opts -- "$WASICAML/js/main.js" "$@"
