#! /bin/sh

export WASICAML='%ROOT%'
export WASICAML_CWD=`pwd`

# other interesting options:
# --wasm-enforce-bounds-checks
#    useful get always getting a stack trace and not just a "bus error"

opts="--stack-trace-limit=1000"
if node --experimental-wasm-bigint -e '' >/dev/null 2>&1; then
    opts="$opts --experimental-wasm-bigint"
fi
if node --experimental-wasm-return-call -e '' >/dev/null 2>&1; then
    opts="$opts --experimental-wasm-return-call"
fi
if node --experimental-wasm-eh -e '' >/dev/null 2>&1; then
    opts="$opts --experimental-wasm-eh"
fi

exec node --stack-size=$(( $(ulimit -s) - 256)) --no-warnings $opts -- "$WASICAML/js/main.js" "$@"
