version: 2
jobs:
  build:
    docker:
      - image: cimg/node:lts
    environment:
      - ARCH: linux
      - GCLOUD_VERSION: 309.0.0
    steps:
    - checkout
    - run: ./ci/install-gcloud
    - run: echo 'export PATH=$HOME/ci:$PATH' >> $BASH_ENV
    - run: ./configure
    - run: make
    - run: make test
    - run: ci/ensure-gcloud-creds
    - run: ci/upload_web
