version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts
    environment:
      - ARCH: linux
      - GCLOUD_VERSION: 309.0.0
    steps:
    - checkout
    - run: ./ci/install-gcloud
    - run: echo 'export PATH=$HOME/ci:$PATH' >> $BASH_ENV
    - run: ./configure
    - run: make
    - run: ulimit -s 16384 && make test
    - run: make test-tail-calls
    - run: ci/ensure-gcloud-creds
    - run: ci/upload_web

workflows:
  build:
    jobs:
      - build:
          context: rmx-prod-uploads
